### ISSUE TITLE
Resolve internal issues

### ISSUE THREAD

**Issue by llopez005** [UMM-CSci-3601-S17/digital-display-garden-iteration-2-boysngirl#6]
Open path problem

**Comment by llopez005** [comment]
Lenny's new code has fixed issue with absolute path address. Other typos in code base have been corrected as well. Documentation was provided by Lenny on Slack.

**Comment by llopez005** [comment]
Merging issues between code bases might appear at merge time and they will be addressed in this issue.

**Comment by llopez005** [comment]
Internal issue that needs to be taken care of: when selecting a flower in **any** bed, the **last** flower always appears as the selected one. List of flowers are shown correctly but does not display the **selected** flower.

**Comment by real-mj-song** [comment]
1. Use routing for different flower pages.
2. Reset like/dislike buttons and comment box when a different flower is selected.

**Comment by real-mj-song** [comment]
Theoretically you could drop a comment/rating, leave the flower, and come back and drop another comment/rating. Might require some way to check if a specific user has left a comment/rating on this flower already.
